config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: %i[registrations passwords confirmations unlocks]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, :user_groups, :permission_resources

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group_permission.rb
# 群組權限
class GroupPermission < ApplicationRecord
  PRIORITY_OPTIONS = {
    disable: 0,
    readable: 1,
    writable: 2
  }
  belongs_to :user_group
  belongs_to :permission_resource
  scope :enable, -> { where('group_permissions.priority > 0') }
  enum priority: PRIORITY_OPTIONS

  before_create :setup_priority

  private

  def setup_priority
    self.priority = permission_resource.default_priority if priority.nil?
  end
end

# == Schema Information
#
# Table name: group_permissions
#
#  id                     :bigint           not null, primary key
#  priority               :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  permission_resource_id :bigint           not null
#  user_group_id          :bigint           not null
#
# Indexes
#
#  index_group_permissions_on_permission_resource_id  (permission_resource_id)
#  index_group_permissions_on_priority                (priority)
#  index_group_permissions_on_user_group_id           (user_group_id)
#
# Foreign Keys
#
#  fk_rails_...  (permission_resource_id => permission_resources.id)
#  fk_rails_...  (user_group_id => user_groups.id)
#

app/models/permission_resource.rb
# 權限資源
class PermissionResource < ApplicationRecord
  has_many :group_permissions, dependent: :destroy
  enum default_priority: GroupPermission::PRIORITY_OPTIONS

  after_create :setup_group_sermissions

  private

  def setup_group_sermissions
    UserGroup.all.each do |user_group|
      user_group.permission_resources += [self]
    end
  end
end

# == Schema Information
#
# Table name: permission_resources
#
#  id               :bigint           not null, primary key
#  default_priority :integer          default("disable")
#  name             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_permission_resources_on_default_priority  (default_priority)
#

app/models/user.rb
class User < ApplicationRecord
  belongs_to :user_group
  has_many :enabled_permissions, through: :user_group
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_group_id          :bigint
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_user_group_id         (user_group_id)
#

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_many :users
  has_many :group_permissions, dependent: :destroy
  accepts_nested_attributes_for :group_permissions
  has_many :permission_resources, through: :group_permissions
  has_many :enabled_permissions, -> { enable }, class_name: 'GroupPermission'
  has_many :enabled_resources, through: :enabled_permissions
end

# == Schema Information
#
# Table name: user_groups
#
#  id          :bigint           not null, primary key
#  name        :string
#  super_admin :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_user_groups_on_super_admin  (super_admin)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/authed_controller.rb
class AuthedController < ApplicationController
  before_action :authenticate_user!
  before_action :setup_authorize

  private

  def setup_authorize
    authorize self.class.name.demodulize.to_s.gsub('Controller', '').singularize.constantize
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/permission_resources_controller.rb
class PermissionResourcesController < AuthedController
  helper_method :permission_resource
  def index
    @permission_resources = PermissionResource.all
  end

  def show

  end

  def new
    @permission_resource = PermissionResource.new
  end

  def create
    @permission_resource = PermissionResource.new(permit_attribute)
    @permission_resource.save

    redirect_to url_for(action: :index)
  end

  def edit

  end

  def update
    permission_resource.update(permit_attribute)
    redirect_to url_for(action: :index)
  end

  def destroy
    permission_resource.destroy
    redirect_to url_for(action: :index)
  end

  private

  def permission_resource
    @permission_resource ||= PermissionResource.find(params[:id])
  end

  def permit_attribute
    params.require(:permission_resource).permit(
      :name,
      :default_priority
    )
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < AuthedController
  helper_method :user_group
  def index
    @user_groups = UserGroup.all
  end

  def show
    @users = user_group.users
  end

  def new
    @user_group = UserGroup.new

    PermissionResource.all.each do |permission_resource|
      @user_group.group_permissions.new(permission_resource: permission_resource, priority: permission_resource.default_priority)
    end
  end

  def create
    @user_group = UserGroup.new(permit_attribute)
    @user_group.save

    redirect_to url_for(action: :index)
  end

  def edit

  end

  def update
    user_group.update(permit_attribute)
    redirect_to url_for(action: :index)
  end

  def destroy
    user_group.destroy
    redirect_to url_for(action: :index)
  end

  private

  def user_group
    @user_group ||= UserGroup.includes(:permission_resources).find(params[:id])
  end

  def permit_attribute
    params.require(:user_group).permit(
      :name,
      :super_admin,
      group_permissions_attributes: %i[id priority permission_resource_id]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < AuthedController
  helper_method :user
  def index
    @users = User.all.includes(:user_group)
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(permit_attribute)
    @user.save

    redirect_to url_for(action: :index)
  end

  def edit

  end

  def update
    user.update(permit_attribute)
    redirect_to url_for(action: :index)
  end

  def destroy
    user.destroy
    redirect_to url_for(action: :index)
  end

  private

  def user
    @user ||= User.find(params[:id])
  end

  def permit_attribute
    params.require(:user).permit(
      :email,
      :user_group_id,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authed_helper.rb
module AuthedHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/permission_resources_helper.rb
module PermissionResourcesHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authed/edit.html.erb
<%= render 'form'%>

app/views/authed/new.html.erb
<%= render 'form'%>

app/views/common/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to User.model_name.human, users_path, class: 'nav-link' if policy(User).index?%>
        </li>
        <li class="nav-item">
          <%= link_to UserGroup.model_name.human, user_groups_path, class: 'nav-link' if policy(UserGroup).index?%>
        </li>
        <li class="nav-item">
          <%= link_to PermissionResource.model_name.human, permission_resources_path, class: 'nav-link' if policy(PermissionResource).index?%>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to '登入', new_user_session_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoPermission</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="container">
    <% flash.each do |type, message|%>
    <div class="alert alert-warning"><%= message%></div>
    <% end %>
    <%= render partial: 'common/header'%>
    <%= yield %>
  </body>
</html>

app/views/permission_resources/_form.html.erb
<%= form_for(permission_resource, html: { class: 'my-3' }) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :priority %>
  <%= f.select :default_priority, collection: PermissionResource.default_priorities.keys %>
  <%= f.submit%>
<% end %>

app/views/permission_resources/_permission_resource.html.erb
<tr>
  <td><%= link_to permission_resource.name,  permission_resource%></td>
  <td><%= permission_resource.default_priority %></td>
</tr>

app/views/permission_resources/index.html.erb
<%= link_to 'New', new_permission_resource_path, class: 'btn btn-primary' if policy(@permission_resources).new?%>
<table class="my-3 table table-stripped">
  <thead>
    <tr>
      <th>name</th>
      <th>default_priority</th>
    </tr>
  </thead>
  <tbody>
    <%= render @permission_resources%>
  </tbody>
</table>

app/views/permission_resources/show.html.erb
<dl class="row my-3">
  <dt class="col-sm-3">Name</dt>
  <dd class="col-sm-9"><%= permission_resource.name %></dd>

  <dt class="col-sm-3">Super Admin</dt>
  <dd class="col-sm-9">
    <%= permission_resource.default_priority %>
  </dd>
</dl>

app/views/user_groups/_form.html.erb
<%= form_for(user_group, html: { class: 'my-3' }) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :super_admin %>
  <%= f.check_box :super_admin %>
  <%= f.fields_for :group_permissions do |group_permission_form|%>
    <div class="my-3">
      <%= group_permission_form.object.permission_resource.name %>
      <%= group_permission_form.hidden_field :permission_resource_id%>
      <%= group_permission_form.label :priority%>
      <%= group_permission_form.select :priority, collection: GroupPermission.priorities.keys %>
    </div>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/user_groups/_user_group.html.erb
<tr>
  <td><%= link_to user_group.name, user_group %></td>
</tr>

app/views/user_groups/index.html.erb
<%= link_to 'New', new_user_group_path, class: 'btn btn-primary' if policy(@user_groups).new?%>
<table class="my-3 table table-stripped">
  <thead>
    <tr>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <%= render @user_groups%>
  </tbody>
</table>

app/views/user_groups/show.html.erb
<%= link_to 'edit', edit_user_group_path(user_group), class: 'btn btn-primary' if policy(user_group).edit?%>
<dl class="row my-3">
  <dt class="col-sm-3">Name</dt>
  <dd class="col-sm-9"><%= user_group.name %></dd>

  <dt class="col-sm-3">Super Admin</dt>
  <dd class="col-sm-9">
    <%= user_group.super_admin %>
  </dd>

  <% user_group.group_permissions.each do |group_permission|%>
  <dt class="col-sm-3"><%= group_permission.permission_resource.name %></dt>
  <dd class="col-sm-9">
    <%= group_permission.priority %>
  </dd>
  <% end %>
</dl>

app/views/users/_form.html.erb
<%= form_for(user, html: { class: 'my-3' }) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <% if user.new_record? %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <% end %>
  <%= f.label :user_group_id %>
  <%= f.select :user_group_id, collection: UserGroup.all.pluck(:name, :id) %>
  <%= f.submit %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to user.email,  user%></td>
  <td><%= user.user_group.name %></td>
</tr>

app/views/users/index.html.erb
<%= link_to 'New', new_user_path, class: 'btn btn-primary' if policy(@users).new? %>
<table class="my-3 table table-stripped">
  <thead>
    <tr>
      <th>name</th>
      <th>user group</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users%>
  </tbody>
</table>

app/views/users/show.html.erb
<%= link_to 'edit', edit_user_path(user), class: 'btn btn-primary' if policy(user).edit?%>
<dl class="row my-3">
  <dt class="col-sm-3">Email</dt>
  <dd class="col-sm-9"><%= user.email %></dd>

  <dt class="col-sm-3">User Group</dt>
  <dd class="col-sm-9">
    <%= user.user_group.name %>
  </dd>
</dl>